import { ActivatedRoute } from '@angular/router';
import { User } from './../../shared/user.model';
import { ProfileUserService } from './../../contents/profile-user/profile-user.service';
import { DataStorage } from 'src/app/shared/data-storage.service';
import { ModalViewLayoutComponent } from './modal-view-layout/modal-view-layout.component';
import { EditorService } from './editor.service';
import { ArticlePage } from './../../shared/article-page.model';
import { FormGroup, FormControl, FormBuilder } from '@angular/forms';
import { Component, OnInit, ViewChild, ElementRef, OnDestroy, AfterViewInit } from '@angular/core';
import { Subscription, Observable } from 'rxjs';
import { MDBModalService, MDBModalRef } from 'angular-bootstrap-md';
import Quill from 'quill';


const Parchment = Quill.import('parchment');
const PttkEditor = new Parchment.Attributor.Class('pttk-editor', 'pttk-editor');
Quill.register(PttkEditor);

@Component({
  selector: 'app-editor',
  templateUrl: './editor.component.html',
  styleUrls: ['./editor.component.scss', './editor.component.css']
})
export class EditorComponent implements OnInit, OnDestroy {
  // zwraca cały comonent EditorLayoutComponent z wszystkimi polami
  // i metodami
  @ViewChild('appEditorLayout', { static: false }) editorLayout?;
  @ViewChild('appEditorPage', { static: false }) editorPage?;
  idSubscrtition: Subscription;
  subscriptionUser: Subscription;
  subscriptionData: Subscription;
  editorLayoutModal;
  editorPageModal;
  editorForm: FormGroup;
  contentView;
  titleHeader;
  isModal = false;
  id;
  user: User;
  isEditMode = false;
  // editorLayout: FormGroup;

  constructor(private modalService: MDBModalService,
              private dataStorage: DataStorage,
              private profileUserService: ProfileUserService,
              private route: ActivatedRoute) {}


    // subscription: Subscription;
    article: ArticlePage;
    modalRef: MDBModalRef; // service modal window

  ngOnInit(): void {

    this.editorForm = new FormGroup({
      editor: new FormControl(null),
    });
    this.id = this.route.snapshot.params.id;
    if (this.id !== undefined) {
      this.isEditMode = true;
      console.log('id', this.id);
    }
    this.subscriptionUser = this.profileUserService.getProfileUserObs$().subscribe(
      user => {
        this.user = user;
        console.log('this.user.id', this.user.id);
      }
    );
    if (!this.isEditMode) {
      this.id = this.dataStorage.getNewAutoGeneratedIdFromDB();
    } else {
      // const article = this.dataStorage.article;
      this.subscriptionData = this.dataStorage.getArticleById(this.id).subscribe((article: ArticlePage) => {
      const instanceEditorLayout: Quill = this.editorLayout.editorInstance;
      const instanceEditorPage: Quill = this.editorPage.editorInstance;
      console.log('article.articleLayout', article.articleLayout);
      console.log('articleLayout', this.editorLayout);
      console.log('instanceEditorLayout', instanceEditorLayout);
      this.editorLayout.editorInstance.setContents(article.articleLayout, 'user');
      this.editorPage.editorInstance.setContents(article.articlePage, 'user');
      });
      // console.log('this.id, getArticleById', this.id);
    }
    // const node = document.createElement('div');
    // node.append('Czytaj');
    // PttkEditor.add(node, 'layout');
    // console.log(node.outerHTML);
  }

  onClickView(event) {
    event.preventDefault();
    console.log('editorLayout', this.editorLayout);
    this.editorLayout.onView();
  }

  /* service for modal window
    date: object Delta from Quill editor
  */
  openModalLayout(event) {
    event.preventDefault();
    this.isModal = true;
    this.changeQuillEditor(this.isModal);
    const modalOptions = {
      backdrop: true,
      keyboard: true,
      focus: true,
      show: false,
      ignoreBackdropClick: false,
      class: 'modal-dialog-centered modal-lg',
      containerClass: '',
      animated: true,
      data: {
        heading: 'Modal heading',
        content: this.editorLayout.editor
      }
    };
    this.modalRef = this.modalService.show(ModalViewLayoutComponent,
      modalOptions);
    // this.editorLayout.editor.editor.setContents(cloneEditorInstance);
  }

  private changeQuillEditor(isModal: boolean) {
    const instanceEditorLayout: Quill = this.editorLayout.editorInstance;
    const instanceEditorPage: Quill = this.editorPage.editorInstance;
    let range = instanceEditorLayout.getLength();
    const firstParagraph = instanceEditorPage.getText(0, 168);
    const firstParagraphLayout = instanceEditorLayout.getText(0, 168);
    // console.log('firstParagraphLayout', firstParagraphLayout);
    this.titleHeader = firstParagraphLayout;
    console.log('firstParagraph', firstParagraph);
    const format = instanceEditorLayout.getFormat(range - 5);
    if (!format['pttk-editor']) {
      if (!isModal) {
        instanceEditorLayout.insertText(range, firstParagraph + '...', 'user');
        range = instanceEditorLayout.getLength();
        instanceEditorLayout.insertText(range, 'Czytaj dalej...', {
        size: 'large',
        routerLink:  '/article/' + this.id
      }, 'user');
        instanceEditorLayout.formatLine(range, range, 'pttk-editor', 'layout');
        instanceEditorLayout.insertEmbed(range, 'divider', true, 'user');
        instanceEditorLayout.formatLine(range, range, 'align', 'right');
    }
    }
  }

  onSubmit() {
    this.isModal = false;
    this.changeQuillEditor(this.isModal);
    const article = new ArticlePage();
    article.articleLayout = this.editorLayout.editor.content;
    article.articlePage = this.editorPage.editor.content;
    article.header = this.titleHeader;
    article.id = this.id;
    article.uid = this.user.id;
    article.createDate = new Date().toLocaleString();
    this.dataStorage.storeArticleAPI(article);
  }

  ngOnDestroy(): void {
    if (!this.isEditMode) {
     this.subscriptionUser.unsubscribe();
    } else {
      // this.subscriptionData.unsubscribe();
    }
  }
}




  // private changeQuillEditor1(isModal: boolean) {
  //   let instanceEditorLayout;
  //   let instanceEditorPage;
  //   if (isModal) {
  //     this.editorLayoutModal = cloneDeep(this.editorLayout);
  //     this.editorPageModal = cloneDeep(this.editorPage);
  //     instanceEditorPage = this.editorPageModal.editor.editor;
  //     instanceEditorLayout = this.editorLayoutModal.editor.editor;
  //   } else {
  //     instanceEditorLayout = this.editorLayout.editor.editor;
  //     instanceEditorPage = this.editorPage.editor.editor;
  //   }
  //   let range = instanceEditorLayout.getLength();
  //   const firstParagraph = instanceEditorPage.getText(0, 168);
  //   console.log('firstParagraph', firstParagraph);
  //   const format = instanceEditorLayout.getFormat(range - 5);
  //   if (!format['pttk-editor']) {
  //     instanceEditorLayout.insertText(range, firstParagraph + '...', 'user');
  //     range = instanceEditorLayout.getLength();
  //     instanceEditorLayout.insertText(range, 'Czytaj dalej...', {
  //       size: 'large',
  //       link: '/article/' + this.id
  //     }, 'user');
  //     instanceEditorLayout.formatLine(range, range, 'pttk-editor', 'layout');
  //     instanceEditorLayout.insertEmbed(range, 'divider', true, 'user');
  //     instanceEditorLayout.formatLine(range, range, 'align', 'right');
  //   }
  // }


  //  deep<T>(value: T): T {
  //     if (typeof value !== 'object' || value === null) {
  //       return value;
  //     }
  //     if (Array.isArray(value)) {
  //       return this.deepArray(value);
  //     }
  //     return this.deepObject(value);
  //    }

  //  deepObject<T>(source: T) {
  //     const result = {};
  //     Object.keys(source).forEach((key) => {
  //       const value = source[key];
  //       result[key] = this.deep(value);
  //     }, {});
  //     return result as T;
  //    }

  //    deepArray<T extends any[]>(collection: T) {
  //     return collection.map((value) => {
  //       return this.deep(value);
  //     });
  //    }
